[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saurabh Bhandari", email = "saurbhbhandari@referloan.in" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.128.8",
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
py = "py:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
